# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474dce80cec4c37215eb86741ac295e606d8e159b0e82364b2433a2c6639c2541e463f68efe1ad593c558d07a48f8f9c4f219ce59be424cf6e64d459d3ee8a92

test:
  secret_key_base: 157fba3e7bf05fe7f4fd91c449d56fe429450416829fac72ed8c99f873bfc49810c969fafeb640483687bd1b48a192910b8daf5bc73ffd935b59750ecc12b179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
